version: '3'
services:
  nginx:
    image: projects-nginx:latest
    build: ./
    container_name: gateway
    volumes:
      - /Users/santorui/Desktop/Lusofona/projects-server/nginx-proxy/locations:/etc/nginx/locations
      - /Users/santorui/Desktop/Lusofona/projects-server/nginx-proxy/multimedia:/etc/nginx/multimedia
    ports:
      - "80:80"
      - "443:443"
    networks:
      - gateway-network

networks:
  gateway-network:
    external: true
