version: '3'
services:
  nginx:
    image: lusofona-gateway:latest
    build: ./
    container_name: gateway
    volumes:
      - /home/deisi/lusofona-gateway/locations:/etc/nginx/locations
      - /home/deisi/lusofona-gateway/multimedia:/etc/nginx/multimedia
      - /home/deisi/certs/:/home/certs/
    ports:
      - "443:443"
    networks:
      - gateway-network

networks:
  gateway-network:
    external: true
